# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_config"
version = "0.5.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "User configuration of CLInvoice."

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice_config"

[dependencies]
clinvoice_error = {branch = "release/0.3", git = "https://github.com/Iron-E/clinvoice_error"}
clinvoice_schema = {branch = "release/0.8", features = ["serde_support"], git = "https://github.com/Iron-E/clinvoice_schema"}

dirs = "3"
humantime-serde = "1"
serde = {features = ["derive"], version = "1"}
thiserror = "1"
toml = "0.5"

[dev-dependencies]
pretty_assertions = "1"
